# Generated by Django 5.2.4 on 2025-07-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(null=True, upload_to='listimages'),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to='taskimages'),
        ),
    ]
