# Generated by Django 5.2.4 on 2025-07-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='userid',
            new_name='user',
        ),
    ]
